config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :homestays, only: %i[index show new create] do
    resources :bookings, only: :create
  end
  namespace :owner do
    resources :bookings, only: :index
  end
  resources :bookings, only: %i[index update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :homestay
  validates :booking_start, presence: true
  validates :booking_end, presence: true
  enum status: { pending: 'Pending', confirm: 'Confirm', decline: 'Decline' }, _default: :pending

  def pending?
    status == 'pending'
  end
end

app/models/homestay.rb
class Homestay < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_address,
    against: :address,
    using: {
      tsearch: { prefix: true }
    }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  acts_as_taggable_on :tags

  validates :price, presence: true
  validates :address, presence: true
  validates :accomodation, inclusion: { in: ["Apartment", "House"] }
  validates :number_of_users, presence: true, numericality: { less_than_or_equal_to: 4 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :homestays, dependent: :destroy

  has_many :bookings_as_owner, through: :homestays, source: :bookings
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

 # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @booking = Booking.new
    @user = User.new
    @homestay = Homestay.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.homestay = Homestay.find(params[:homestay_id])
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:user, :homestay, :status, :booking_end, :booking_start, :number_of_guests)
  end
end

app/controllers/homestays_controller.rb
class HomestaysController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @homestays =
      if params[:query].present?
        policy_scope(Homestay).search_by_address(params[:query])
      else
        policy_scope(Homestay)
      end

    @markers = @homestays.geocoded.map do |homestay|
      {
        lat: homestay.latitude,
        lng: homestay.longitude
      }
    end


    @tags = ActsAsTaggableOn::Tag.all

    @homestays = @homestays.tagged_with(params[:tags]) if params[:tags]&.any?
  end

  def show
    @homestay = Homestay.find(params[:id])
    authorize @homestay
    @booking = Booking.new
  end

  def new
    @homestay = Homestay.new
    @user = User.new
    @homestay.user = current_user
    authorize @homestay
  end

  def create
    @homestay = Homestay.new(homestay_params)
    @homestay.user = current_user
    authorize @homestay
    if @homestay.save
      redirect_to homestays_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def homestay_params
    params.require(:homestay).permit(:name, :tag_list, :number_of_users, :comments, :price, :availability, :family_description, :accomodation, :address, photos: [])
  end

end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  def index
    @bookings = policy_scope([:owner, Booking])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="f-container">
  <div class="form-container mt-3">
    <h1>Book home</h1>
    <%= simple_form_for [@homestay, @booking] do |f| %>
      <%= f.input :booking_start, as: :date, label: "Start Date" %>
      <%= f.input :booking_end, as: :date, label: "End Date" %>
      <%= f.input :number_of_guests %>
      <%= f.submit 'Add', class: 'btn' %>
    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="d-flex flex-column justify-content-between" style="min-height: 100vh;">
  <div>
    <div>
      <h3>Upcoming Trips 🎉</h3>
    </div>
    <div class="cards">
      <% @bookings.each do |booking| %>
        <div class="card-product">
          <img src="https://i.ibb.co/C8jn6Np/8ed47c5c-e6cd-46a5-98ad-530a6e3bc404.webp" />
          <div class="d-flex w-100 justify-content-between">
            <div class="card-product-infos">
              <h2><%= booking.user.last_name %> Family</h2>
              <p><strong>Wadi Rum, Aqaba Governorate, Jordan</strong></p>
            </div>
            <div>
              <%= link_to "Confirmed", "#", class: "btn btn-ghost disabled "%>
            </div>
          </div>
        </div>
        <h3>
        </h3>
      <% end %>
    </div>
  </div>
  <div class="d-flex flex-column justify-content-between" style="min-height: 100vh;">
    <div>
      <div>
<div class="all-bookings">
  <h1><strong>Upcoming Trips</strong> 🎉 </h1>
  <% @bookings.each do |booking| %>
    <div class="card-with-info">
      <img class="family-photo" src= <%= booking.homestay.photos.attached? ? cl_image_path(booking.homestay.photos.first.key) : booking.homestay.img_url %>/>
      <div class="info-about-family">
        <h2><%= booking.homestay.user.last_name %> Family</h2>
        <p><strong><%= booking.homestay.address %></strong></p>
        <p><%= booking.booking_start %> - <%= booking.booking_end%></p>
      </div>
      <div class="card-status">
        <% if booking.status == "confirm" %>
          <p class="green-color"><%= booking.status %>ed</p>
        <% elsif booking.status == "decline" %>
          <p class="red-color"><%= booking.status %>d</p>
        <% else %>
          <p class="pending"><%= booking.status %></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<%= render 'bookings/form', booking: @booking %>

app/views/homestays/_card_img.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="<%=@homestay.photos.attached? ? cl_image_path(@homestay.photos.first.key) : @homestay.img_url %>" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="<%=@homestay.photos.attached? ? cl_image_path(@homestay.photos.second.key) : @homestay.img_url %>" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="<%=@homestay.photos.attached? ? cl_image_path(@homestay.photos.third.key) : @homestay.img_url %>" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/homestays/_filter.html.erb
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        Filters
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body bg-white">
        <%= form_with method: :get, url: homestays_path do %>
          <% @tags.each do |tag| %>
            <div class="form-check">
              <input name="tags[]" class="form-check-input" type="checkbox" value="<%= tag.name %>" id="flexCheckDefault<%= tag.name %>" <%= "checked" if params[:tags]&.include?(tag.name) %>>
              <label class="form-check-label" for="flexCheckDefault<%= tag.name %>">
                <%= tag.name %>
            </label>
            </div>
          <% end %>
          <%= submit_tag 'Submit', class:"btn btn-primary mt-2 justify-content center" %>
        <% end %>
      </div>
    </div>
  </div>
</div>



<%# <div class="dropdown sticky-top">
  <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
    Filters
  </button>
  <ul class="dropdown-menu p-2" aria-labelledby="dropdownMenu2">
    <li>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
          No Kids
        </label>
      </div>
    </li>
    <li>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
          No Pets
        </label>
      </div>
    </li>
    <li>
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
          No Smoking
        </label>
      </div>
    </li>
  </ul>
</div> %>

app/views/homestays/_form.html.erb
<div class="form-container-homestay ">
  <h1>Add new homeplace</h1>
  <%= simple_form_for @homestay do |f| %>
    <%= f.input :address, placeholder: "Address" %>
    <%= f.input :accomodation, collection: ["Apartment", "House"] %>
    <%= f.input :price, placeholder: "$$$" %>
    <%= f.input :family_description, placeholder: "Write a short story about your family" %>
    <%= f.input :comments, placeholder: "Comments on your home" %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :number_of_users, placeholder: "How many people would your family like to host?", label: "Number of guests" %>
    <%= f.input :tag_list, as: :check_boxes, collection: [ "No Smoking",  "No Pets", "No Kids", "Has Pets", "Has Kids"], label: "Options" %>
    <%= f.submit 'Add' %>
  <% end %>
</div>

app/views/homestays/_homestay_card.html.erb
<div class="card-homestay">
  <div class="img-text">
    <img class="resize-img" src=<%=homestay.photos.attached? ? cl_image_path(homestay.photos.first.key) : homestay.img_url %> alt="family picture">
    <div class="bottom-left">
      <h2><%= homestay.address%></h2>
    </div>
  </div>
  <div class="card-homestay-infos text-black">
    <h2>The <%= homestay.user.last_name %> Family</h2>
    <p><%= homestay.family_description.truncate(40) %></p>
    <div class="bottom-right">
      <p><b>$<%= homestay.price %></b></p>
    </div>
  </div>
</div>

app/views/homestays/index.html.erb
<div class="homestays-container container-map">
  <div class="container mt-3 text-justify">
    <div class="message ps-2 pb-3">
      <h1><b>Discover the world!</b></h1>
      <p>Start your next adventure with...</p>
    </div>
    <div class="cards">
      <% @homestays.each do |homestay|  %>
        <%= link_to homestay_path(homestay), class:"text-decoration-none" do %>
          <%= render 'homestay_card', homestay: homestay %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="container mt-5">
    <div class="right-container">
      <div class="filter px-4 pb-5">
        <%= render 'filter' %>
      </div>
      <div id="map"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/homestays/new.html.erb
<%= render 'homestays/form', homestay: @homestay %>

app/views/homestays/show.html.erb
<div class="container-show">
  <%= link_to "Go back ↩", homestays_path, class: 'card-back-link'%>
  <div class="card-home-info">
    <div class="card-home-photos">
      <div class="home-maine-photo", style="background-image: url(<%=@homestay.photos.attached? ? cl_image_path(@homestay.photos.first.key) : @homestay.img_url %>);">
      </div>
      <div class="home-photos">
        <div class="photo">
          <% if @homestay.photos.count > 1 %>
            <% @homestay.photos[1..-1].each do |photo| %>
              <%= cl_image_tag(photo.key) %>
            <% end %>
          <% else %>
            <%= image_tag('https://media.istockphoto.com/id/155666671/vector/vector-illustration-of-red-house-icon.jpg?s=612x612&w=0&k=20&c=tBqaabvmjFOBVUibZxbd8oWJqrFR5dy-l2bEDJMtZ40=')%>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card-home-description">
      <h2> Location:
        <%= @homestay.address %> </h2>
      <div class="options">
        <% @homestay.tag_list.each do |tag| %>
          <p class="option"> <%= tag %> </p>
        <% end %>
      </div>
      <p><strong>Type of accomodation:</strong> <%= @homestay.accomodation %></p>
      <div>
        <p><strong>A small comment about our home:</strong> <%= @homestay.comments %></p>
      </div>
    </div>
  </div>
  <div class="card-owner-info">
    <div class="card-booking-form">
      <%= render 'bookings/form',homestay: @homestay,booking: @booking  %>
    </div>
    <div class="card-owner-information">
      <div class="card-photo-name">
        <div class="user-avatar", style="background-image: url(<%=@homestay.user.img_url %>);">
        </div>
        <div class="full-name">
          <h2> <%= @homestay.user.first_name %>
            <%= @homestay.user.last_name %>
          </div>
        </div>
      </h2>
      <div class="card-family-description">
        <h2><strong> Age:</strong> <%= @homestay.user.age %> </h2>
        <p><strong>Gender:</strong>  <%= @homestay.user.gender %> </p>
        <p><strong>About the family:</strong> <%= @homestay.family_description %></p>
        <p><strong>About myself: </strong><%= @homestay.user.description %></p>
        <script>
          src="app/javascript/controllers/image_modal_controller.js">
        </script>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homestopia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hammersmith+One&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital@1&display=swap" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>
  <body>
    <%= render "devise/shared/navbar" %>
    <%= render "devise/shared/flashes" %>
    <div class="content"><%= yield %></div>
    <%= render "devise/shared/footbar" %>
  </body>
</html>

app/views/owner/bookings/index.html.erb
<div class="container">
  <h1 class="flip-card-title">Possible Candidates</h1>
  <div class="row flip-container">
    <% @bookings.each do |booking| %>
      <div class="card flip-card" style="width: 24rem;">
        <div class="flip-card-inner">
          <div class="flip-card-front">
            <div class="flip-card-img-overlay card-body" style="background-image: url(<%= booking.user.img_url %>)">
              <div class="row content-status-flip">
                <i class="fa-solid fa-rotate-left card-font-left"></i>
                <% if booking.status == "confirm" %>
                  <p class="card-font-right green"><%= booking.status %>ed</p>
                <% elsif booking.status == "decline" %>
                  <p class="card-font-right red"><%= booking.status %>d</p>
                <% else %>
                  <p class="card-font-right"><%= booking.status %></p>
                <% end %>
              </div>
              <h3 class="inner-card-content card-text" > <%= booking.user.first_name %> <%= booking.user.last_name %> </h3>
            </div>
          </div>
          <div class="flip-card-back align-items-center d-flex justify-content-center">
            <div class="booking-actions">
              <% if booking.pending? %>
                <%= simple_form_for booking do |f| %>
                  <%= f.input :status, as: :hidden, input_html: { value: 'confirm'} %>
                  <%= f.submit 'Accept', class: 'btn btn-info accept' %>
                <% end %>
                <%= simple_form_for booking do |f| %>
                  <%= f.input :status, as: :hidden, input_html: { value: 'decline'} %>
                  <%= f.submit 'Decline', class: 'btn btn-light decline' %>
                <% end %>
              <% else %>
                <% if booking.status == "confirm" %>
                  <p class="booking-status green"><%= booking.status %>ed</p>
                <% elsif booking.status == "decline" %>
                  <p class="booking-status red"><%= booking.status %>d</p>
                <% else %>
                  <p class="booking-status"><%= booking.status %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="card-border">
          <div class="d-flex justify-content-between">
            <p class="m-2 booking-tag"> <i class="fa-regular fa-envelope"></i> : <%= booking.user.email %></p>
          </div>
          <div class="d-flex justify-content-between">
            <p class="m-2 booking-tag"> <i class="fa-solid fa-calendar"></i> : <%= booking.booking_start.strftime("%A, %b %d") %> ~ <%= booking.booking_end.strftime("%A, %b %d") %> </p>
            <p class="m-2 booking-tag"> <i class="fa-sharp fa-solid fa-dollar-sign"></i> : <%= booking.homestay.price %> </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <meta name=”viewport” content=”width=device-width, initial-scale=1.0″>
    <h1>Homestopia</h1>
    <div class="typing-effect">
      <p>Be with family anywhere in the world</p>
    </div>
    <%= link_to "Discover", homestays_path, class: "bubbly-button fw-bold" %>
  </button>
</div>
</div>
<div class="body py-4" id="home-body">
  <div class="container">
    <h2 class="align-text-center">Travel Around the World</h2>
    <p class="align-text-center">Live with a local family and learn a new culture first-hand.</p>
  </div>
</div>
<div class="d-flex justify-content-between" id="carousel">
  <%= render "devise/shared/carousel" %>
</div>